# Generated by Django 4.2.30 on 2026-07-31 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='category',
            field=models.CharField(choices=[('বীজ', 'বীজ'), ('চারাগাছ', 'চারাগাছ'), ('টব', 'টব'), ('সার', 'সার'), ('টুলস', 'পার্টনার টুলস')], max_length=50),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace_items/'),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
