# Generated by Django 4.2.30 on 2026-07-31 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('water', 'পানি দেওয়ার সময়'), ('fertilizer', 'সার দেওয়ার সময়'), ('pruning', 'ছাঁটাইয়ের সময়'), ('disease', 'রোগ সনাক্ত!'), ('community', 'নতুন কমিউনিটি পোস্ট'), ('tip', 'উদ্ভিদ পরিচর্যা টিপস')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
