# Generated by Django 4.2.30 on 2026-07-31 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='master_plants/')),
                ('description', models.TextField(blank=True, null=True)),
                ('suitable_sunlight', models.CharField(blank=True, max_length=100, null=True)),
                ('suitable_season', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='name_bn',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='suitable_season',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='suitable_sunlight',
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('মাঝারি', 'মাঝারি'), ('ছাদ', 'ছাদ'), ('বারান্দা', 'বারান্দা'), ('ঘর', 'ঘর'), ('বাগান', 'বাগান')], default='বারান্দা', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='nickname',
            field=models.CharField(default='গাছ', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.CharField(default='চারাগাছ', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userplant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userplant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_plants/'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='planted_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='PlantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('পানি দেওয়া', 'পানি দেওয়া'), ('সার দেওয়া', 'সার দেওয়া'), ('ছাঁটাই', 'ছাঁটাই'), ('কীটনাশক', 'কীটনাশক')], max_length=50)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('due_time', models.TimeField(default=datetime.time(9, 0))),
                ('repeat_frequency', models.CharField(choices=[('একবার', 'একবার'), ('দৈনিক', 'দৈনিক'), ('সপ্তাহে একবার', 'সপ্তাহে একবার'), ('মাসে একবার', 'মাসে একবার')], default='একবার', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plants.plant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userplant',
            name='plant_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='plants.masterplant'),
        ),
    ]
