# Generated by Django 4.2.30 on 2026-07-31 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_masterplant_remove_plant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPlantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('plant_name_bn', models.CharField(max_length=100)),
                ('plant_name_en', models.CharField(max_length=100)),
                ('sunlight', models.CharField(max_length=50)),
                ('space', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('watering_info', models.TextField()),
                ('fertilizer_info', models.TextField()),
                ('harvest_time', models.TextField()),
                ('growth_time', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('care_tips', models.TextField()),
                ('extra_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_recommendations/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
